version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=breweryadmin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=brewerydb
    ports:
      - '5432:5432'